main:
  components_repository: 'https://github.com/vitorbeltrao/census-income-forecast#components'
  project_name: rental-prices-ny
  experiment_name: development
  steps: all

# 01_upload_raw_data:
#   input_uri : 'https://archive.ics.uci.edu/ml/machine-learning-databases/adult/adult.data'

# 02_transform_raw_data:
#   input_artifact: "vitorabdo/census-income-forecast/raw_data:latest"
#   test_size: 0.2
#   random_seed: 42
#   stratify_by: "none"

# 04_basic_clean:
#   input_artifact: "vitorabdo/census-income-forecast/train_set:latest"
#   race: " Other"

# 05_data_check:
#   csv: "vitorabdo/census-income-forecast/clean_data:latest"

06_train_model:
  # input_artifact: "vitorabdo/census-income-forecast/clean_data:latest"
  # cv: 5
  # scoring: "f1"
  random_forest:
    n_estimators: 50
    max_depth: 10

# 07_test_model:
#   mlflow_model: "vitorabdo/census-income-forecast/final_model_pipe:prod"
#   test_data: "vitorabdo/census-income-forecast/test_set:latest"